2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_setup.py:_flush():75] Loading settings from /home/soroosh/.config/wandb/settings
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_setup.py:_flush():75] Loading settings from /home/soroosh/Programmes/DD/DD_package/wandb/settings
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'DD_package/main.py', 'program': '/home/soroosh/Programmes/DD/DD_package/main.py'}
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_init.py:_log_setup():386] Logging user logs to /home/soroosh/Programmes/DD/DD_package/wandb/run-20220221_165540-1pah92xu/logs/debug.log
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_init.py:_log_setup():387] Logging internal logs to /home/soroosh/Programmes/DD/DD_package/wandb/run-20220221_165540-1pah92xu/logs/debug-internal.log
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_init.py:init():420] calling init triggers
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {'C': 0.7314620360344091, 'fit_intercept': False, 'l1_ratio': 0.7010754851775808, 'max_iter': 98740, 'penalty': 'l2', 'solver': 'saga', 'multi_class': 'multinomial'}
2022-02-21 16:55:40,728 INFO    MainThread:160069 [wandb_init.py:init():471] starting backend
2022-02-21 16:55:40,729 INFO    MainThread:160069 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-21 16:55:40,729 INFO    MainThread:160069 [backend.py:ensure_launched():219] starting backend process...
2022-02-21 16:55:40,732 INFO    MainThread:160069 [backend.py:ensure_launched():224] started backend process with pid: 160104
2022-02-21 16:55:40,733 INFO    MainThread:160069 [wandb_init.py:init():480] backend started and connected
2022-02-21 16:55:40,735 INFO    MainThread:160069 [wandb_init.py:init():550] updated telemetry
2022-02-21 16:55:40,744 INFO    MainThread:160069 [wandb_init.py:init():581] communicating current version
2022-02-21 16:55:41,297 INFO    MainThread:160069 [wandb_init.py:init():586] got version response 
2022-02-21 16:55:41,297 INFO    MainThread:160069 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-21 16:56:11,298 INFO    MainThread:160069 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-02-21 16:56:11,298 ERROR   MainThread:160069 [wandb_init.py:init():601] backend process timed out
2022-02-21 16:56:11,298 ERROR   MainThread:160069 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-21 16:56:11,304 ERROR   MainThread:160069 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 614, in init
    backend.cleanup()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/soroosh/venv_Jan2022/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
