Traceback (most recent call last):
  File "/home/soroosh/Programmes/DD/DD_package/main.py", line 723, in <module>
    clu_est.fit_test_tuned_estimator()
  File "/home/soroosh/Programmes/DD/DD_package/dd_package/models/clustering_estimators.py", line 301, in fit_test_tuned_estimator
    self.estimator.fit(v["x_train"], v["y_train"])
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_spectral.py", line 533, in fit
    self.affinity_matrix_ = pairwise_kernels(X, metric=self.affinity,
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/metrics/pairwise.py", line 1954, in pairwise_kernels
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/metrics/pairwise.py", line 1359, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/metrics/pairwise.py", line 1105, in rbf_kernel
    K = euclidean_distances(X, Y, squared=True)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/metrics/pairwise.py", line 313, in euclidean_distances
    distances = - 2 * safe_sparse_dot(X, Y.T, dense_output=True)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/soroosh/anaconda3/lib/python3.9/site-packages/sklearn/utils/extmath.py", line 152, in safe_sparse_dot
    ret = a @ b
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 306. GiB for an array with shape (202815, 202815) and data type float64